/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Keypoints.h
  Source: /home/alan/Desktop/deploy/CycloneDDS_example/cyclonedds-0.10.5/build/bin/Keypoints.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_KEYPOINTS_H
#define DDSC_KEYPOINTS_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct mujoco_visualization_KeypointsMsg
{
  float keypoints[90];
} mujoco_visualization_KeypointsMsg;

extern const dds_topic_descriptor_t mujoco_visualization_KeypointsMsg_desc;

#define mujoco_visualization_KeypointsMsg__alloc() \
((mujoco_visualization_KeypointsMsg*) dds_alloc (sizeof (mujoco_visualization_KeypointsMsg)));

#define mujoco_visualization_KeypointsMsg_free(d,o) \
dds_sample_free ((d), &mujoco_visualization_KeypointsMsg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_KEYPOINTS_H */
