/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: MocapMsg.h
  Source: /mnt/nvme1/Desktop/deploy/CycloneDDS_example/cyclonedds-0.10.5/build/bin/MocapMsg.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_MOCAPMSG_H
#define DDSC_MOCAPMSG_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct MocapMsg
{
  float fps;
  float root_rot[4];
  float box_rot[8];
  float key_points[27];
  uint8_t teleop;
  float teleop_obs[810];
  uint8_t hands;
  float left_hand_pos[21];
  float right_hand_pos[21];
  float left_wrist_rot[4];
  float right_wrist_rot[4];
  uint8_t retarget;
  float hands_joints[14];
  float left_wrist_joints[3];
  float right_wrist_joints[3];
} MocapMsg;

extern const dds_topic_descriptor_t MocapMsg_desc;

#define MocapMsg__alloc() \
((MocapMsg*) dds_alloc (sizeof (MocapMsg)));

#define MocapMsg_free(d,o) \
dds_sample_free ((d), &MocapMsg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_MOCAPMSG_H */
