# 
policy_path: "resources/policies/g1/motion.pt"
xml_path: "resources/robots/g1_description/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002

# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                  -0.1,  0.0,  0.0,  0.3, -0.2, 0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 47

cmd_init: [0.5, 0, 0]

# custom
robot_name: "g1"
on_rack: false
world_type: multi-skill challenge # plain # only used for simulation
urdf_path: "resources/robots/g1_description/g1_12dof_raisim_obj.urdf"
homing_timesteps: 100
homing:
  pos: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0, -0.1, 0.0, 0.0, 0.3, -0.2, 0.0]
  kp:  [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
  kd:  [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]

terrain_config_file: config/course_config.yaml
