# 
policy_path: "resources/policies/g1/motion.pt"
xml_path: "resources/robots/g1_description/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.001
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                  -0.1,  0.0,  0.0,  0.3, -0.2, 0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 47

cmd_init: [0.5, 0, 0]

# custom
robot_name: "HuOreo"
on_rack: false
world_type: plain # only used for simulation
urdf_path: "resources/robots/HuOreo/urdf/HuOreo.urdf"
homing_timesteps: 100
homing:
  pos: [-0.08, -0.06, -0.42, 0.94, -0.52, 0.06,
        0.08,  0.06, -0.42, 0.94, -0.52, -0.06,
        0, 0, 0, 0, 0, 0, 0, 0]
  kp:  [500, 300, 500, 500, 200, 200,
        500, 300, 500, 500, 200, 200,
        800, 100, 100, 100, 100, 100, 100, 100]
  kd:  [5, 3, 10, 10, 4, 4,
        5, 3, 10, 10, 4, 4,
        16, 2, 2, 2, 2, 2, 2, 2]

init_base_position: [0.0, 0.0, 1.16]
init_base_orientation:  [1.0, 0.0, 0.0, 0.0]  # 单位四元数