policy_path: "resources/policies/mdl/policy_waq.pt"
engine_path: "resources/policies/mdl/policy_waq.engine"
xml_path: "resources/robots/mdl/urdf/scene_stair.xml"

# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30]
kds: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

default_angles: [0, 0.8, -1.5,
                 0, 0.8, -1.5,
                 0, 0.8, -1.5,
                 0, 0.8, -1.5]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 45

cmd_init: [0, 0, 0]
max_cmd: [1, 1, 1.57]
robot_name: mdl