policy_path: "resources/policies/mdl/policy_waq.pt"
engine_path: "resources/policies/mdl/policy_waq.engine"
xml_path: "resources/robots/mdl/urdf/scene_stair.xml"
simulation_dt: 0.002
control_decimation: 10

kps: [30, 30, 20, 30, 30, 20, 30, 30, 20, 30, 30, 20]
kds: [1,  1,  0.5, 1, 1,  0.5, 1, 1,  0.5, 1, 1,  0.5]

default_angles: [
  0, 0.6, -1.55,
  0, 0.6, -1.55,
  0, 0.8, -1.55,
  0, 0.8, -1.55,
]

transfer_joint_angles: [
  0., 1.2, -2.7, 
  -0., 1.2, -2.7, 
  0., 2.2, -2.7, 
  -0., 2.2, -2.7
]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 45
num_hidden: 225

cmd_init: [0, 0, 0]
max_cmd: [1, 1, 1.57]
robot_name: mdl

# dds related
lowcmd_topic: "/low_level/motor/cmd"
lowstate_topic: "/low_level/lowstate"
imu_topic: "/low_level/imu/state"
motor_topic: "/low_level/motor/state"

domain_id: 10
print_interval: 300
lowstate_pub_hz: 800